apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-connect-obs
  namespace: dynatrace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-connect-obs
rules:
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list","patch","update","create"]
  - apiGroups:
      - "core.openfeature.dev"
    resources:
      - featureflags
      - featureflagsources
      - flagds
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
    - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - nodes/stats
      - nodes/proxy
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-connect-obs
roleRef:
  kind: ClusterRole
  name: edge-connect-obs
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: edge-connect-obs
    namespace: dynatrace
---
apiVersion: dynatrace.com/v1alpha2
kind: EdgeConnect
metadata:
  name: CODESPACE_NAME
  namespace: dynatrace
spec:
  apiServer: DYNATRACE_APPS_URL
  serviceAccountName: edge-connect-obs
  replicas: 1
  oauth:
    provisioner: true
    clientSecret: edge-connect-CODESPACE_NAME-credentials
    endpoint: https://DYNATRACE_SSO_URL
    resource: "urn:dtaccount:DYNATRACE_ACCOUNT_ID"
  kubernetesAutomation:
    enabled: true