apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vegas-casino

resources:
  - namespace.yaml
  - configmap.yaml
  - slots-deployment.yaml
  - roulette-deployment.yaml
  - dice-deployment.yaml
  - blackjack-deployment.yaml
  - frontend-deployment.yaml
  - gateway-deployment.yaml
  - scoring-deployment.yaml
  - dashboard-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: vegas-casino
  app.kubernetes.io/part-of: vegas-casino-microservices
  app.kubernetes.io/managed-by: kustomize





