{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vegas-casino.fullname" . }}-postgresql
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vegas-casino.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: {{ include "vegas-casino.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql
{{- end }}








