{{- if .Values.scoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vegas-casino.fullname" . }}-scoring
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vegas-casino.labels" . | nindent 4 }}
    app.kubernetes.io/component: scoring
spec:
  type: {{ .Values.scoring.service.type }}
  ports:
    - port: {{ .Values.scoring.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vegas-casino.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scoring
{{- end }}








